// =============================================================================
// Data Types
// =============================================================================

export interface Approval {
  id: string
  type: 'deliverable' | 'estimate' | 'draft'
  title: string
  description: string
  createdBy: string
  createdAt: string
  workOrderId: string
  workOrderTitle: string
  projectTitle: string
  priority: 'high' | 'medium' | 'low'
  dueDate: string
}

export interface Task {
  id: string
  title: string
  description: string
  status: 'todo' | 'in_progress' | 'completed'
  priority: 'high' | 'medium' | 'low'
  dueDate: string
  isOverdue: boolean
  assignedTo: string
  workOrderId: string
  workOrderTitle: string
  projectTitle: string
  estimatedHours: number
}

export interface Blocker {
  id: string
  type: 'task' | 'work_order'
  title: string
  reason: 'waiting_on_external' | 'missing_information' | 'technical_issue' | 'waiting_on_approval'
  blockerDetails: string
  blockedSince: string
  workOrderId: string
  workOrderTitle: string
  projectTitle: string
  priority: 'high' | 'medium' | 'low'
  assignedTo: string
}

export interface UpcomingDeadline {
  id: string
  title: string
  projectTitle: string
  dueDate: string
  daysUntilDue: number
  status: 'draft' | 'planning' | 'in_progress' | 'review' | 'completed'
  progress: number
  priority: 'high' | 'medium' | 'low'
  assignedTeam: string[]
}

export interface Activity {
  id: string
  type: 'task_completed' | 'approval_created' | 'comment_added' | 'deliverable_submitted' | 'blocker_flagged' | 'task_started' | 'time_logged' | 'work_order_created'
  title: string
  description: string
  timestamp: string
  user: string
  workOrderTitle: string
  projectTitle: string
}

export interface DailySummary {
  generatedAt: string
  summary: string
  priorities: string[]
  suggestedFocus: string
}

export interface Metrics {
  tasksCompletedToday: number
  tasksCompletedThisWeek: number
  approvalsPending: number
  hoursLoggedToday: number
  activeBlockers: number
}

// =============================================================================
// Quick Capture Types
// =============================================================================

export type QuickCaptureType = 'request' | 'note' | 'task'

export interface QuickCaptureData {
  type: QuickCaptureType
  content: string
}

// =============================================================================
// Component Props
// =============================================================================

export interface TodayProps {
  /** Daily summary generated by PM Copilot */
  dailySummary: DailySummary

  /** Approvals awaiting review */
  approvals: Approval[]

  /** Tasks assigned to user that are due today or overdue */
  tasks: Task[]

  /** Items flagged as blocked across all projects */
  blockers: Blocker[]

  /** Work orders with deadlines in the next 7 days */
  upcomingDeadlines: UpcomingDeadline[]

  /** Recent activity feed showing what happened since last login */
  activities: Activity[]

  /** Key metrics for the dashboard */
  metrics: Metrics

  /** Called when user wants to view an approval's details */
  onViewApproval?: (id: string) => void

  /** Called when user approves an approval request */
  onApprove?: (id: string) => void

  /** Called when user rejects an approval request */
  onReject?: (id: string, reason?: string) => void

  /** Called when user wants to view a task's details */
  onViewTask?: (id: string) => void

  /** Called when user marks a task as complete */
  onCompleteTask?: (id: string) => void

  /** Called when user updates a task's status */
  onUpdateTask?: (id: string, status: Task['status']) => void

  /** Called when user wants to view a blocker's details */
  onViewBlocker?: (id: string) => void

  /** Called when user resolves a blocker */
  onResolveBlocker?: (id: string) => void

  /** Called when user escalates a blocker */
  onEscalateBlocker?: (id: string) => void

  /** Called when user wants to view a work order's details */
  onViewWorkOrder?: (id: string) => void

  /** Called when user wants to view an activity's details */
  onViewActivity?: (id: string) => void

  /** Called when user submits a quick capture entry */
  onQuickCapture?: (data: QuickCaptureData) => void

  /** Called when user refreshes the daily summary */
  onRefreshSummary?: () => void
}
