<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Agents\Workflows\PMCopilotWorkflow;
use App\Http\Requests\ApproveSuggestionRequest;
use App\Http\Requests\RejectSuggestionRequest;
use App\Http\Requests\TriggerPMCopilotRequest;
use App\Models\AgentWorkflowState;
use App\Models\InboxItem;
use App\Models\Project;
use App\Models\WorkOrder;
use App\Services\AgentApprovalService;
use App\Services\AgentOrchestrator;
use App\Services\ProjectInsightsService;
use App\ValueObjects\DeliverableSuggestion;
use App\ValueObjects\TaskSuggestion;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Log;

/**
 * Controller for PM Copilot AI agent functionality.
 *
 * Handles triggering PM Copilot workflows, retrieving suggestions,
 * and processing approval/rejection of generated deliverables and tasks.
 */
class PMCopilotController extends Controller
{
    public function __construct(
        private readonly AgentOrchestrator $orchestrator,
        private readonly AgentApprovalService $approvalService,
    ) {}

    /**
     * Start PM Copilot workflow for a work order.
     *
     * Creates and initiates a PMCopilotWorkflow to analyze the work order
     * and generate deliverable and task suggestions.
     */
    public function trigger(TriggerPMCopilotRequest $request, WorkOrder $workOrder): JsonResponse
    {
        $this->authorize('view', $workOrder);

        try {
            // Create the workflow state
            $workflowState = $this->orchestrator->invokePMCopilot($workOrder);

            Log::info('PM Copilot triggered via API', [
                'work_order_id' => $workOrder->id,
                'workflow_state_id' => $workflowState->id,
                'user_id' => $request->user()->id,
            ]);

            // Try to run the workflow, but don't fail if it encounters issues
            $status = 'started';
            try {
                $workflow = new PMCopilotWorkflow($this->orchestrator, $this->approvalService);
                $workflow->setCurrentState($workflowState);
                $workflow->run();

                $workflowState->refresh();
                $status = $workflowState->isCompleted() ? 'completed' : ($workflowState->isPaused() ? 'paused' : 'running');
            } catch (\Throwable $workflowError) {
                Log::warning('PM Copilot workflow execution encountered an error', [
                    'work_order_id' => $workOrder->id,
                    'workflow_state_id' => $workflowState->id,
                    'error' => $workflowError->getMessage(),
                ]);
                $status = 'error';
            }

            return response()->json([
                'success' => true,
                'message' => 'PM Copilot workflow started',
                'workflow_state_id' => $workflowState->id,
                'status' => $status,
            ]);
        } catch (\Throwable $e) {
            Log::error('PM Copilot trigger failed', [
                'work_order_id' => $workOrder->id,
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);

            return response()->json([
                'success' => false,
                'message' => 'Failed to start PM Copilot workflow',
                'error' => $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Get generated suggestions for a work order.
     *
     * Returns deliverable and task suggestions generated by the PM Copilot
     * workflow for review and approval.
     */
    public function getSuggestions(WorkOrder $workOrder): JsonResponse
    {
        $this->authorize('view', $workOrder);

        // Find the most recent workflow state for this work order
        $workflowState = AgentWorkflowState::query()
            ->where('workflow_class', PMCopilotWorkflow::class)
            ->whereJsonContains('state_data->input->work_order_id', $workOrder->id)
            ->latest()
            ->first();

        if ($workflowState === null) {
            return response()->json([
                'success' => false,
                'message' => 'No PM Copilot workflow found for this work order',
                'deliverable_suggestions' => [],
                'task_suggestions' => [],
            ], 404);
        }

        $stateData = $workflowState->state_data ?? [];
        $deliverableSuggestions = $stateData['deliverable_suggestions'] ?? [];
        $taskSuggestions = $stateData['task_suggestions'] ?? [];

        return response()->json([
            'success' => true,
            'workflow_state_id' => $workflowState->id,
            'status' => $workflowState->isCompleted() ? 'completed' : ($workflowState->isPaused() ? 'paused' : 'running'),
            'deliverable_suggestions' => $deliverableSuggestions,
            'task_suggestions' => $taskSuggestions,
        ]);
    }

    /**
     * Approve a generated suggestion.
     *
     * Creates the approved deliverable or task from the suggestion
     * and marks the corresponding inbox item as approved.
     */
    public function approveSuggestion(ApproveSuggestionRequest $request, InboxItem $suggestion): JsonResponse
    {
        // Verify the inbox item belongs to user's team
        if ($suggestion->team_id !== $request->user()->currentTeam->id) {
            return response()->json([
                'success' => false,
                'message' => 'Unauthorized',
            ], 403);
        }

        $suggestionType = $request->validated('suggestion_type');
        $suggestionIndex = $request->validated('suggestion_index');

        // Get the workflow state associated with this inbox item
        /** @var AgentWorkflowState|null $workflowState */
        $workflowState = $suggestion->approvable;

        if ($workflowState === null || ! $workflowState instanceof AgentWorkflowState) {
            return response()->json([
                'success' => false,
                'message' => 'Invalid suggestion reference',
            ], 400);
        }

        $stateData = $workflowState->state_data ?? [];
        $workOrderId = $stateData['input']['work_order_id'] ?? null;

        if ($workOrderId === null) {
            return response()->json([
                'success' => false,
                'message' => 'Work order not found in workflow state',
            ], 400);
        }

        $workOrder = WorkOrder::find($workOrderId);

        if ($workOrder === null) {
            return response()->json([
                'success' => false,
                'message' => 'Work order not found',
            ], 404);
        }

        try {
            if ($suggestionType === 'deliverable') {
                $this->approveDeliverableSuggestion($workflowState, $suggestionIndex, $workOrder);
            } elseif ($suggestionType === 'task') {
                $this->approveTaskSuggestion($workflowState, $suggestionIndex, $workOrder);
            } else {
                return response()->json([
                    'success' => false,
                    'message' => 'Invalid suggestion type',
                ], 400);
            }

            // Mark the inbox item as approved
            $suggestion->markAsApproved();

            Log::info('PM Copilot suggestion approved', [
                'inbox_item_id' => $suggestion->id,
                'suggestion_type' => $suggestionType,
                'suggestion_index' => $suggestionIndex,
                'work_order_id' => $workOrderId,
                'user_id' => $request->user()->id,
            ]);

            return response()->json([
                'success' => true,
                'message' => 'Suggestion approved',
            ]);
        } catch (\Throwable $e) {
            Log::error('PM Copilot suggestion approval failed', [
                'inbox_item_id' => $suggestion->id,
                'error' => $e->getMessage(),
            ]);

            return response()->json([
                'success' => false,
                'message' => 'Failed to approve suggestion',
                'error' => $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Reject a generated suggestion.
     *
     * Marks the suggestion as rejected with the provided reason
     * and updates the corresponding inbox item.
     */
    public function rejectSuggestion(RejectSuggestionRequest $request, InboxItem $suggestion): JsonResponse
    {
        // Verify the inbox item belongs to user's team
        if ($suggestion->team_id !== $request->user()->currentTeam->id) {
            return response()->json([
                'success' => false,
                'message' => 'Unauthorized',
            ], 403);
        }

        $suggestionType = $request->validated('suggestion_type');
        $suggestionIndex = $request->validated('suggestion_index');
        $reason = $request->validated('reason');

        // Get the workflow state associated with this inbox item
        /** @var AgentWorkflowState|null $workflowState */
        $workflowState = $suggestion->approvable;

        if ($workflowState === null || ! $workflowState instanceof AgentWorkflowState) {
            return response()->json([
                'success' => false,
                'message' => 'Invalid suggestion reference',
            ], 400);
        }

        try {
            // Update the workflow state with rejection info
            $stateData = $workflowState->state_data ?? [];

            if ($suggestionType === 'deliverable') {
                $stateData['rejected_deliverables'] = $stateData['rejected_deliverables'] ?? [];
                $stateData['rejected_deliverables'][] = [
                    'index' => $suggestionIndex,
                    'reason' => $reason,
                    'rejected_at' => now()->toIso8601String(),
                    'rejected_by' => $request->user()->id,
                ];
            } elseif ($suggestionType === 'task') {
                $stateData['rejected_tasks'] = $stateData['rejected_tasks'] ?? [];
                $stateData['rejected_tasks'][] = [
                    'index' => $suggestionIndex,
                    'reason' => $reason,
                    'rejected_at' => now()->toIso8601String(),
                    'rejected_by' => $request->user()->id,
                ];
            }

            $workflowState->update(['state_data' => $stateData]);

            // Mark the inbox item as rejected
            $suggestion->markAsRejected();

            Log::info('PM Copilot suggestion rejected', [
                'inbox_item_id' => $suggestion->id,
                'suggestion_type' => $suggestionType,
                'suggestion_index' => $suggestionIndex,
                'reason' => $reason,
                'user_id' => $request->user()->id,
            ]);

            return response()->json([
                'success' => true,
                'message' => 'Suggestion rejected',
            ]);
        } catch (\Throwable $e) {
            Log::error('PM Copilot suggestion rejection failed', [
                'inbox_item_id' => $suggestion->id,
                'error' => $e->getMessage(),
            ]);

            return response()->json([
                'success' => false,
                'message' => 'Failed to reject suggestion',
                'error' => $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Get project insights generated by AI analysis.
     *
     * Returns insights about overdue items, bottlenecks, scope creep,
     * and resource reallocation suggestions for the project.
     */
    public function getProjectInsights(Project $project, ProjectInsightsService $insightsService): JsonResponse
    {
        $this->authorize('view', $project);

        try {
            $insights = $insightsService->generateInsights($project);

            return response()->json([
                'success' => true,
                'insights' => array_map(fn ($insight) => $insight->toArray(), $insights),
            ]);
        } catch (\Throwable $e) {
            Log::error('Failed to generate project insights', [
                'project_id' => $project->id,
                'error' => $e->getMessage(),
            ]);

            return response()->json([
                'success' => false,
                'message' => 'Failed to generate project insights',
                'error' => $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Approve and create a deliverable from suggestion.
     */
    private function approveDeliverableSuggestion(
        AgentWorkflowState $workflowState,
        int $suggestionIndex,
        WorkOrder $workOrder
    ): void {
        $stateData = $workflowState->state_data ?? [];
        $suggestions = $stateData['deliverable_suggestions'] ?? [];

        if (! isset($suggestions[$suggestionIndex])) {
            throw new \InvalidArgumentException("Deliverable suggestion at index {$suggestionIndex} not found");
        }

        $suggestionData = $suggestions[$suggestionIndex];
        $deliverableSuggestion = DeliverableSuggestion::fromArray($suggestionData);

        // Create the deliverable
        $deliverableSuggestion->createDeliverable($workOrder);

        // Mark this suggestion as approved in state data
        $stateData['approved_deliverables'] = $stateData['approved_deliverables'] ?? [];
        $stateData['approved_deliverables'][] = $suggestionIndex;
        $workflowState->update(['state_data' => $stateData]);
    }

    /**
     * Approve and create tasks from suggestion.
     */
    private function approveTaskSuggestion(
        AgentWorkflowState $workflowState,
        int $suggestionIndex,
        WorkOrder $workOrder
    ): void {
        $stateData = $workflowState->state_data ?? [];
        $suggestions = $stateData['task_suggestions'] ?? [];

        if (! isset($suggestions[$suggestionIndex])) {
            throw new \InvalidArgumentException("Task suggestion at index {$suggestionIndex} not found");
        }

        $suggestionData = $suggestions[$suggestionIndex];
        $tasks = $suggestionData['tasks'] ?? [];

        // Create each task in the suggestion
        foreach ($tasks as $taskData) {
            $taskSuggestion = TaskSuggestion::fromArray($taskData);
            $taskSuggestion->createTask($workOrder);
        }

        // Mark this suggestion as approved in state data
        $stateData['approved_tasks'] = $stateData['approved_tasks'] ?? [];
        $stateData['approved_tasks'][] = $suggestionIndex;
        $workflowState->update(['state_data' => $stateData]);
    }
}
